-- Generated by drizzle-kit, then COMPLETED where the generator asked and
-- re-sequenced so each statement can run. Two gaps in its output:
--   1. It emitted the driver_profiles primary-key drop commented out
--      ("we can't automatically get name for primary key ... paste pk name
--      manually"). The name is the PostgreSQL default for the inline
--      `"user_id" uuid PRIMARY KEY` in 0000_initial.sql — driver_profiles_pkey.
--   2. It ordered the widened PRIMARY KEY rebuilds BEFORE the ADD COLUMNs the
--      new keys are built from.
-- The statements below are the generator's own, unchanged in content;
-- 0020_snapshot.json is its output untouched.
ALTER TABLE "car_members" DROP CONSTRAINT "car_members_driver_user_id_driver_profiles_user_id_fk";--> statement-breakpoint
ALTER TABLE "car_members" ADD COLUMN "cycle" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "driver_profiles" ADD COLUMN "cycle" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "team_memberships" ADD COLUMN "cycle" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "car_members" DROP CONSTRAINT "car_members_driver_user_id_member_user_id_pk";--> statement-breakpoint
ALTER TABLE "team_memberships" DROP CONSTRAINT "team_memberships_user_id_team_pk";--> statement-breakpoint
ALTER TABLE "driver_profiles" DROP CONSTRAINT "driver_profiles_pkey";--> statement-breakpoint
ALTER TABLE "driver_profiles" ADD CONSTRAINT "driver_profiles_user_id_cycle_pk" PRIMARY KEY("user_id","cycle");--> statement-breakpoint
ALTER TABLE "car_members" ADD CONSTRAINT "car_members_driver_user_id_member_user_id_cycle_pk" PRIMARY KEY("driver_user_id","member_user_id","cycle");--> statement-breakpoint
ALTER TABLE "team_memberships" ADD CONSTRAINT "team_memberships_user_id_team_cycle_pk" PRIMARY KEY("user_id","team","cycle");--> statement-breakpoint
ALTER TABLE "car_members" ADD CONSTRAINT "car_members_driver_cycle_fk" FOREIGN KEY ("driver_user_id","cycle") REFERENCES "public"."driver_profiles"("user_id","cycle") ON DELETE cascade ON UPDATE cascade;
