-- Generated by drizzle-kit, then COMPLETED where the generator asked and
-- re-sequenced so each statement can run, as 0020 was:
--   1. It emitted the team_budgets primary-key drop commented out. The name is
--      the PostgreSQL default for the inline `"team" "team" PRIMARY KEY` in
--      0000_initial.sql: team_budgets_pkey.
--   2. It ordered the widened PRIMARY KEY BEFORE the ADD COLUMN it is built on.
-- Then one data step, below the generator's statements: rows that already
-- exist on a camp that has named its year move into that year. On a camp that
-- has not, they keep the sentinel, and setFoundingYear adopts them.
-- 0034_snapshot.json is the generator's output untouched.
ALTER TABLE "adoptees" ADD COLUMN "cycle" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "team_budgets" ADD COLUMN "cycle" integer DEFAULT 1 NOT NULL;--> statement-breakpoint
ALTER TABLE "team_budgets" DROP CONSTRAINT "team_budgets_pkey";--> statement-breakpoint
ALTER TABLE "team_budgets" ADD CONSTRAINT "team_budgets_team_cycle_pk" PRIMARY KEY("team","cycle");--> statement-breakpoint
CREATE UNIQUE INDEX "adoptees_cycle_slot_idx" ON "adoptees" USING btree ("cycle","slot_number");--> statement-breakpoint
-- The camp's year, as currentCycle() picks it: the one open year when exactly
-- one is open, otherwise the latest. NULL on a camp with no year, which leaves
-- the sentinel in place.
WITH cycles AS (
  SELECT (c->>'year')::int AS year, c->>'endedAt' AS ended_at
  FROM camp_settings, jsonb_array_elements(
    CASE WHEN jsonb_typeof(config->'cycles') = 'array' THEN config->'cycles' ELSE '[]'::jsonb END
  ) AS c
  WHERE c->>'year' ~ '^[0-9]{4}$'
), current_year AS (
  SELECT COALESCE(
    (SELECT min(year) FROM cycles WHERE ended_at IS NULL HAVING count(*) = 1),
    (SELECT max(year) FROM cycles)
  ) AS year
)
UPDATE "team_budgets" SET "cycle" = current_year.year
FROM current_year
WHERE current_year.year IS NOT NULL AND "team_budgets"."cycle" = 1;--> statement-breakpoint
WITH cycles AS (
  SELECT (c->>'year')::int AS year, c->>'endedAt' AS ended_at
  FROM camp_settings, jsonb_array_elements(
    CASE WHEN jsonb_typeof(config->'cycles') = 'array' THEN config->'cycles' ELSE '[]'::jsonb END
  ) AS c
  WHERE c->>'year' ~ '^[0-9]{4}$'
), current_year AS (
  SELECT COALESCE(
    (SELECT min(year) FROM cycles WHERE ended_at IS NULL HAVING count(*) = 1),
    (SELECT max(year) FROM cycles)
  ) AS year
)
UPDATE "adoptees" SET "cycle" = current_year.year
FROM current_year
WHERE current_year.year IS NOT NULL AND "adoptees"."cycle" = 1;
