-- Custom SQL migration file, put your code below! --
-- Kitchen 1 (#243) replaces the recipe lifecycle. The old statuses were
-- pending, analysing, ready, scheduled and rejected; the new ones are
-- suggested, changes_requested, approved, queued, analysing, proofread,
-- accepted and rejected. The next migration (generated by drizzle-kit) drops
-- the recipe_status type and builds the new one, casting the column back with
-- USING. That cast fails on any stored value the new type does not know, so
-- this migration first turns the column into plain text and maps every old
-- value onto a new one:
--   pending                      -> suggested (nobody has looked at it yet)
--   analysing, ready, scheduled  -> approved
--   rejected                     -> rejected (unchanged)
-- The old recipes/analyse cron was a stub, so no row was ever really analysed.
-- Approved sends nothing anywhere: a captain still has to press Run.
--
-- The default goes first, because a default typed as the old enum would stop
-- the type from being dropped. The UPDATE touches only rows still holding an
-- old value, so a re-run changes nothing.
ALTER TABLE "recipes" ALTER COLUMN "status" DROP DEFAULT;
--> statement-breakpoint
ALTER TABLE "recipes" ALTER COLUMN "status" SET DATA TYPE text;
--> statement-breakpoint
UPDATE "recipes"
SET "status" = CASE
  WHEN "status" = 'pending' THEN 'suggested'
  WHEN "status" IN ('analysing', 'ready', 'scheduled') THEN 'approved'
  ELSE "status"
END
WHERE "status" IN ('pending', 'analysing', 'ready', 'scheduled');
